package exceptions.runtimeexception;

public class RunTimeException1 {
    public static void main(String[] args) {
        try{

        }catch (RuntimeException e){

        //}catch (ArithmeticException){

        }finally {
            System.out.println("done");
        }

    }
}
